import { z } from "zod";

/** A 6-digit email OTP code (trimmed before checking). */
export const OtpTokenSchema = z.string().trim().regex(/^\d{6}$/);

export const SetInputSchema = z.object({
  reps: z.number().int().nonnegative().nullable().optional(),
  weight: z.number().nonnegative().nullable().optional(),
  weight_unit: z.enum(["kg", "lbs"]).nullable().optional(),
  time_seconds: z.number().nonnegative().nullable().optional(),
  distance: z.number().nonnegative().nullable().optional(),
  distance_unit: z.enum(["m", "km", "mi"]).nullable().optional(),
  rpe: z.number().min(1).max(10).nullable().optional(),
  is_warmup: z.boolean().optional(),
  notes: z.string().max(500).nullable().optional(),
});
export type SetInput = z.infer<typeof SetInputSchema>;

export const MetricKindSchema = z.enum([
  "weight_reps",
  "bodyweight_reps",
  "weighted_bodyweight_reps",
  "time_only",
  "time_weight",
  "distance_only",
  "distance_time",
  "none",
]);

/**
 * A workout pasted in for import (e.g. generated by an external AI). Becomes a
 * new session with every exercise and set pre-filled. metric_kind is only used
 * when an exercise must be auto-created; a catalog match overrides it.
 */
export const WorkoutImportSchema = z.object({
  name: z.string().trim().min(1).max(80),
  notes: z.string().max(2000).nullable().optional(),
  exercises: z
    .array(
      z.object({
        name: z.string().trim().min(1).max(120),
        metric_kind: MetricKindSchema.optional(),
        notes: z.string().max(500).nullable().optional(),
        sets: z.array(SetInputSchema).default([]),
      }),
    )
    .min(1, "Add at least one exercise"),
});
export type WorkoutImport = z.infer<typeof WorkoutImportSchema>;

/** A set normalised by buildImportPlan, round-tripped through the review UI. */
const CommitSetSchema = z.object({
  position: z.number().int().nonnegative(),
  reps: z.number().int().nonnegative().nullable(),
  weight: z.number().nonnegative().nullable(),
  weight_unit: z.enum(["kg", "lbs"]).nullable(),
  time_seconds: z.number().nonnegative().nullable(),
  distance: z.number().nonnegative().nullable(),
  distance_unit: z.enum(["m", "km", "mi"]).nullable(),
  rpe: z.number().min(1).max(10).nullable(),
  is_warmup: z.boolean(),
  notes: z.string().max(500).nullable(),
});

const ResolutionSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("match"), exerciseId: z.string().uuid() }),
  z.object({ kind: z.literal("new") }),
]);

/** Untrusted payload posted from the import review screen. */
export const CommitImportSchema = z.object({
  name: z.string().trim().min(1).max(80),
  notes: z.string().max(2000).nullable(),
  exercises: z
    .array(
      z.object({
        name: z.string().trim().min(1).max(120),
        metricKind: MetricKindSchema,
        notes: z.string().max(500).nullable(),
        sets: z.array(CommitSetSchema),
        resolution: ResolutionSchema,
      }),
    )
    .min(1),
});
export type CommitImport = z.infer<typeof CommitImportSchema>;

export const TemplateInputSchema = z.object({
  name: z.string().trim().min(1).max(80),
  notes: z.string().max(2000).nullable().optional(),
});
export type TemplateInput = z.infer<typeof TemplateInputSchema>;

export const SessionDateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);

export const SessionUpdateSchema = z.object({
  name: z.string().trim().min(1).max(80).optional(),
  performed_on: SessionDateSchema.optional(),
  notes: z.string().max(2000).nullable().optional(),
  bodyweight: z.number().positive().nullable().optional(),
  ended_at: z.string().datetime().nullable().optional(),
});
export type SessionUpdate = z.infer<typeof SessionUpdateSchema>;

/**
 * Whitelisted fields the user can edit on a workout_template_exercises row.
 * Excludes structural fields (template_id, exercise_id, position, id) so a
 * malicious client can't repoint rows or collide on the unique position.
 */
export const TemplateExercisePatchSchema = z.object({
  target_sets: z.number().int().nonnegative().nullable().optional(),
  target_reps: z.number().int().nonnegative().nullable().optional(),
  target_weight: z.number().nonnegative().nullable().optional(),
  target_time_seconds: z.number().int().nonnegative().nullable().optional(),
  target_distance: z.number().nonnegative().nullable().optional(),
  target_distance_unit: z.enum(["m", "km", "mi"]).nullable().optional(),
  rest_seconds: z.number().int().nonnegative().nullable().optional(),
  notes: z.string().max(500).nullable().optional(),
});
export type TemplateExercisePatch = z.infer<typeof TemplateExercisePatchSchema>;
